name: Daily run update.py

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  update_tracker_rule:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 复制现有文件以备比较
    - name: Backup existing files
      run: |
        cp ipv4.txt ipv4.txt.bak
        cp ipv6.txt ipv6.txt.bak
        cp host.conf host.conf.bak

    - name: Run update.py
      run: python update.py

    # 检查新旧文件内容是否相同
    - name: Check if files are identical to their backups
      id: check_files
      run: |
       if cmp -s ipv4.txt ipv4.txt.bak && cmp -s ipv6.txt ipv6.txt.bak && cmp -s host.conf host.conf.bak; then
          echo "No changes detected in the files. Exiting..."
          echo "::set-output name=skip_remaining_steps::true"
        else
          echo "Changes detected in the files. Proceeding to commit..."
          echo "::set-output name=skip_remaining_steps::false"
       fi

    - name: Commit and push
      if: steps.check_files.outputs.skip_remaining_steps == 'false'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ipv4.txt ipv6.txt host.conf
        git commit -m "Update Rule" 
        git push
